services:
  database:
    image: mongodb:latest
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: p@5$w0rD
      MONGO_INITDB_DATABASE: PropertyPulse
  property-pulse-web:
    image: property-pulse-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database